-- Create Data Tablespace
CREATE TABLESPACE SHOT_DATA
DATAFILE 'C:\APP\TESSY\ORADATA\THUR_27632_TESSY_SHOT_DB\SHOT_DATA02.DBF'
SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE 2G;

-- Create Index Tablespace
CREATE TABLESPACE SHOT_INDEX
DATAFILE 'C:\APP\TESSY\ORADATA\THUR_27632_TESSY_SHOT_DB\SHOT_INDEX02.DBF'
SIZE 300M
AUTOEXTEND ON NEXT 50M MAXSIZE 1G;

-- Create Temporary Tablespace
CREATE TEMPORARY TABLESPACE SHOT_TEMP
TEMPFILE 'C:\APP\TESSY\ORADATA\THUR_27632_TESSY_SHOT_DB\SHOT_TEMP01.DBF'
SIZE 200M
AUTOEXTEND ON NEXT 50M MAXSIZE 500M;