-- Connect as SHOT_DBA
CONNECT SHOT_DBA/Tessy@localhost:1521/THUR_27632_Tessy_SHOT_DB

-- DROP ALL EXISTING TABLES IN CORRECT ORDER (child tables first)
BEGIN
    -- Drop tables in reverse order of dependencies
    FOR rec IN (
        SELECT table_name 
        FROM user_tables 
        ORDER BY CASE table_name
            WHEN 'PAYMENT' THEN 1
            WHEN 'PRESCRIPTION_DETAIL' THEN 2
            WHEN 'BILL' THEN 3
            WHEN 'PRESCRIPTION' THEN 4
            WHEN 'CONSULTATION' THEN 5
            WHEN 'APPOINTMENT' THEN 6
            WHEN 'DOCTOR' THEN 7
            WHEN 'DEPARTMENT' THEN 8
            WHEN 'PATIENT' THEN 9
            WHEN 'MEDICATION' THEN 10
            ELSE 11
        END
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS';
            DBMS_OUTPUT.PUT_LINE('Dropped table: ' || rec.table_name);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Error dropping ' || rec.table_name || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/

-- Alternative: Drop all tables at once (more aggressive)
BEGIN
    -- Disable constraints first
    FOR c IN (SELECT table_name, constraint_name 
              FROM user_constraints 
              WHERE constraint_type = 'R') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || 
                         ' DISABLE CONSTRAINT ' || c.constraint_name;
    END LOOP;
    
    -- Drop all tables
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('All tables dropped successfully');
END;
/

-- DROP ALL SEQUENCES TOO
BEGIN
    FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('All sequences dropped successfully');
END;
/

-- Now create sequences according to ER diagram
CREATE SEQUENCE seq_patient_id START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE seq_department_id START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE seq_doctor_id START WITH 2000 INCREMENT BY 1;
CREATE SEQUENCE seq_appointment_id START WITH 3000 INCREMENT BY 1;
CREATE SEQUENCE seq_consultation_id START WITH 4000 INCREMENT BY 1;
CREATE SEQUENCE seq_prescription_id START WITH 5000 INCREMENT BY 1;
CREATE SEQUENCE seq_medication_id START WITH 6000 INCREMENT BY 1;
CREATE SEQUENCE seq_detail_id START WITH 7000 INCREMENT BY 1;
CREATE SEQUENCE seq_bill_id START WITH 8000 INCREMENT BY 1;
CREATE SEQUENCE seq_payment_id START WITH 9000 INCREMENT BY 1;

DBMS_OUTPUT.PUT_LINE('All sequences created successfully');

-- Create tables in correct order (parents first)

-- 1. PATIENT Table
CREATE TABLE PATIENT (
    PATIENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50 BYTE) NOT NULL,
    LAST_NAME VARCHAR2(50 BYTE) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER CHAR(1 BYTE),
    PHONE_NUMBER VARCHAR2(15 BYTE),
    EMAIL VARCHAR2(100 BYTE),
    ADDRESS VARCHAR2(200 BYTE),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
) TABLESPACE SHOT_DATA;

-- 2. DEPARTMENT Table
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100 BYTE) NOT NULL,
    LOCATION VARCHAR2(200 BYTE),
    PHONE_NUMBER VARCHAR2(15 BYTE),
    HEAD_DOCTOR_ID NUMBER
) TABLESPACE SHOT_DATA;

-- 3. DOCTOR Table
CREATE TABLE DOCTOR (
    DOCTOR_ID NUMBER PRIMARY KEY,
    DEPARTMENT_ID NUMBER,
    FIRST_NAME VARCHAR2(50 BYTE) NOT NULL,
    LAST_NAME VARCHAR2(50 BYTE) NOT NULL,
    SPECIALIZATION VARCHAR2(100 BYTE),
    LICENSE_NUMBER VARCHAR2(50 BYTE) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR2(15 BYTE),
    EMAIL VARCHAR2(100 BYTE),
    HIRE_DATE DATE,
    STATUS VARCHAR2(20 BYTE)
) TABLESPACE SHOT_DATA;

-- 4. MEDICATION Table
CREATE TABLE MEDICATION (
    MEDICATION_ID NUMBER PRIMARY KEY,
    MEDICATION_NAME VARCHAR2(100 BYTE) UNIQUE NOT NULL,
    GENERIC_NAME VARCHAR2(100 BYTE),
    MANUFACTURER VARCHAR2(100 BYTE),
    UNIT_PRICE NUMBER(10,2) NOT NULL,
    STOCK_QUANTITY NUMBER NOT NULL,
    REORDER_LEVEL NUMBER,
    EXPIRY_DATE DATE
) TABLESPACE SHOT_DATA;

-- 5. APPOINTMENT Table
CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL,
    DOCTOR_ID NUMBER NOT NULL,
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME VARCHAR2(10 BYTE) NOT NULL,
    STATUS VARCHAR2(20 BYTE),
    NOTES VARCHAR2(500 BYTE),
    CREATED_BY VARCHAR2(50 BYTE),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
) TABLESPACE SHOT_DATA;

-- 6. CONSULTATION Table
CREATE TABLE CONSULTATION (
    CONSULTATION_ID NUMBER PRIMARY KEY,
    APPOINTMENT_ID NUMBER UNIQUE NOT NULL,
    DOCTOR_ID NUMBER NOT NULL,
    DIAGNOSIS VARCHAR2(500 BYTE),
    SYMPTOMS VARCHAR2(500 BYTE),
    CONSULTATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TREATMENT_PLAN VARCHAR2(1000 BYTE),
    FOLLOW_UP_REQUIRED CHAR(1 BYTE),
    CONSULTATION_COST NUMBER(10,2)
) TABLESPACE SHOT_DATA;

-- 7. PRESCRIPTION Table
CREATE TABLE PRESCRIPTION (
    PRESCRIPTION_ID NUMBER PRIMARY KEY,
    CONSULTATION_ID NUMBER NOT NULL,
    PRESCRIPTION_DATE DATE DEFAULT SYSDATE NOT NULL,
    INSTRUCTIONS VARCHAR2(500 BYTE),
    VALID_UNTIL DATE,
    STATUS VARCHAR2(20 BYTE),
    ISSUED_BY NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
) TABLESPACE SHOT_DATA;

-- 8. PRESCRIPTION_DETAIL Table
CREATE TABLE PRESCRIPTION_DETAIL (
    DETAIL_ID NUMBER PRIMARY KEY,
    PRESCRIPTION_ID NUMBER NOT NULL,
    MEDICATION_ID NUMBER NOT NULL,
    DOSAGE VARCHAR2(50 BYTE) NOT NULL,
    FREQUENCY VARCHAR2(100 BYTE) NOT NULL,
    DURATION_DAYS NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    SPECIAL_INSTRUCTIONS VARCHAR2(200 BYTE),
    CONSTRAINT UQ_PRESCRIPTION_MEDICATION 
        UNIQUE (PRESCRIPTION_ID, MEDICATION_ID)
) TABLESPACE SHOT_DATA;

-- 9. BILL Table
CREATE TABLE BILL (
    BILL_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL,
    CONSULTATION_ID NUMBER UNIQUE NOT NULL,
    BILL_DATE DATE DEFAULT SYSDATE NOT NULL,
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    PAID_AMOUNT NUMBER(10,2),
    PAYMENT_STATUS VARCHAR2(20 BYTE),
    PAYMENT_DATE DATE
) TABLESPACE SHOT_DATA;

-- 10. PAYMENT Table
CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER PRIMARY KEY,
    BILL_ID NUMBER NOT NULL,
    PAYMENT_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(30 BYTE),
    TRANSACTION_REF VARCHAR2(100 BYTE),
    PROCESSED_BY VARCHAR2(50 BYTE)
) TABLESPACE SHOT_DATA;

DBMS_OUTPUT.PUT_LINE('All tables created successfully');

-- Now add foreign key constraints
BEGIN
    -- Doctor -> Department
    EXECUTE IMMEDIATE 'ALTER TABLE DOCTOR ADD CONSTRAINT FK_DOCTOR_DEPARTMENT 
        FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)';
    
    -- Department -> Doctor (Head doctor)
    EXECUTE IMMEDIATE 'ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_HEAD_DOCTOR 
        FOREIGN KEY (HEAD_DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)';
    
    -- Appointment -> Patient
    EXECUTE IMMEDIATE 'ALTER TABLE APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_PATIENT 
        FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)';
    
    -- Appointment -> Doctor
    EXECUTE IMMEDIATE 'ALTER TABLE APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_DOCTOR 
        FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)';
    
    -- Consultation -> Appointment
    EXECUTE IMMEDIATE 'ALTER TABLE CONSULTATION ADD CONSTRAINT FK_CONSULTATION_APPOINTMENT 
        FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID)';
    
    -- Consultation -> Doctor
    EXECUTE IMMEDIATE 'ALTER TABLE CONSULTATION ADD CONSTRAINT FK_CONSULTATION_DOCTOR 
        FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)';
    
    -- Prescription -> Consultation
    EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIPTION ADD CONSTRAINT FK_PRESCRIPTION_CONSULTATION 
        FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION(CONSULTATION_ID)';
    
    -- Prescription -> Doctor
    EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIPTION ADD CONSTRAINT FK_PRESCRIPTION_DOCTOR 
        FOREIGN KEY (ISSUED_BY) REFERENCES DOCTOR(DOCTOR_ID)';
    
    -- Prescription_Detail -> Prescription
    EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIPTION_DETAIL ADD CONSTRAINT FK_DETAIL_PRESCRIPTION 
        FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTION(PRESCRIPTION_ID)';
    
    -- Prescription_Detail -> Medication
    EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIPTION_DETAIL ADD CONSTRAINT FK_DETAIL_MEDICATION 
        FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATION(MEDICATION_ID)';
    
    -- Bill -> Patient
    EXECUTE IMMEDIATE 'ALTER TABLE BILL ADD CONSTRAINT FK_BILL_PATIENT 
        FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)';
    
    -- Bill -> Consultation
    EXECUTE IMMEDIATE 'ALTER TABLE BILL ADD CONSTRAINT FK_BILL_CONSULTATION 
        FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION(CONSULTATION_ID)';
    
    -- Payment -> Bill
    EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_BILL 
        FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID)';
    
    DBMS_OUTPUT.PUT_LINE('All foreign key constraints added successfully');
END;
/

-- Create indexes for better performance
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PATIENT_NAME ON PATIENT(FIRST_NAME, LAST_NAME) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DOCTOR_NAME ON DOCTOR(FIRST_NAME, LAST_NAME) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_APPOINTMENT_DATE ON APPOINTMENT(APPOINTMENT_DATE) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONSULTATION_DATE ON CONSULTATION(CONSULTATION_DATE) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BILL_DATE ON BILL(BILL_DATE) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MEDICATION_NAME ON MEDICATION(MEDICATION_NAME) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PRESCRIPTION_DATE ON PRESCRIPTION(PRESCRIPTION_DATE) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PAYMENT_DATE ON PAYMENT(PAYMENT_DATE) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DOCTOR_SPECIALIZATION ON DOCTOR(SPECIALIZATION) TABLESPACE SHOT_INDEX';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_APPOINTMENT_STATUS ON APPOINTMENT(STATUS) TABLESPACE SHOT_INDEX';
    
    DBMS_OUTPUT.PUT_LINE('All indexes created successfully');
END;
/

-- Verify table creation
SELECT table_name, tablespace_name, num_rows 
FROM user_tables 
ORDER BY table_name;

-- Verify sequences
SELECT sequence_name, increment_by, last_number 
FROM user_sequences 
ORDER BY sequence_name;

DBMS_OUTPUT.PUT_LINE('=============================================');
DBMS_OUTPUT.PUT_LINE('ALL TABLES DROPPED AND RECREATED SUCCESSFULLY');
DBMS_OUTPUT.PUT_LINE('According to your ER diagram structure');
DBMS_OUTPUT.PUT_LINE('=============================================');